SLAC/W6-D9

web/themes/gesso/webpack.production.js

@briantschu Give this fix a try and see if it fixes the error you were seeing.

Fix SplitChunksPlugin error

---

.github/workflows/build_deploy_and_test.yml

- [SLAC22-13] Enable builds on main and live
- [SLAC22-13] Turn off behat and visual regression tests

[SLAC22-13] Disable behat and vrt

---

web/themes/gesso/source/03-components/map/map.stories.jsx
web/themes/gesso/source/03-components/map/map.twig
web/themes/gesso/source/03-components/map/map.yml

This might be the smallest component ever.

SLAC22-35 - map iframe embed FED

---

web/themes/gesso/source/03-components/cookie-banner/cookie-banner.es6.js
web/themes/gesso/source/03-components/cookie-banner/cookie-banner.scss
web/themes/gesso/source/03-components/cookie-banner/cookie-banner.stories.jsx
web/themes/gesso/source/03-components/cookie-banner/cookie-banner.twig
web/themes/gesso/source/03-components/cookie-banner/cookie-banner.yml

Seems like the backend of this is still up in the air, haven't added cookie-setting behavior at this time.

[SLAC22-28] - cookie banner

---

web/themes/gesso/source/03-components/figure/_figure.scss
web/themes/gesso/source/03-components/figure/figure.stories.jsx
web/themes/gesso/source/03-components/figure/figure.yml

Used the existing Figure component and just tweaked styling.

[SLAC22-31] - image with caption

---

composer-manifest.yaml
composer.lock
config/sync/core.entity_view_display.node.article.default.yml
config/sync/core.entity_view_display.node.article.teaser.yml
config/sync/core.entity_view_display.user.user.compact.yml
config/sync/core.entity_view_display.user.user.default.yml
config/sync/core.extension.yml
web/sites/default/settings.pantheon.php

- [SLAC22-201] Upgrade Drupal core, contrib, and dependencies
- [SLAC22-201] Config updates

[SLAC22-201] Update Drupal to 9.4.0

---

composer-manifest.yaml
composer.json
composer.lock
config/sync/admin_toolbar.settings.yml
config/sync/admin_toolbar_tools.settings.yml
config/sync/block.block.claro_breadcrumbs.yml
config/sync/block.block.claro_content.yml
config/sync/block.block.claro_help.yml
config/sync/block.block.claro_local_actions.yml
config/sync/block.block.claro_messages.yml
config/sync/block.block.claro_page_title.yml
config/sync/block.block.claro_primary_local_tasks.yml
config/sync/block.block.claro_secondary_local_tasks.yml
config/sync/block.block.gin_breadcrumbs.yml
config/sync/block.block.gin_content.yml
config/sync/block.block.gin_help.yml
config/sync/block.block.gin_local_actions.yml
config/sync/block.block.gin_messages.yml
config/sync/block.block.gin_page_title.yml
config/sync/block.block.gin_primary_local_tasks.yml
config/sync/block.block.gin_secondary_local_tasks.yml
config/sync/claro.settings.yml
config/sync/core.extension.yml
config/sync/gin.settings.yml
config/sync/system.theme.yml

- [SLAC22-200] Make gin and gin toolbar available
- [SLAC22-200] Set gin as default admin theme

[SLAC22-200] Set Gin as admin theme

---

web/themes/gesso/source/03-components/_index.scss
web/themes/gesso/source/03-components/fifty-fifty/_fifty-fifty.scss

206 - add space above & below 50/50

---

web/themes/gesso/source/03-components/figure/_figure.scss
web/themes/gesso/source/03-components/figure/figure--iframe.yml
web/themes/gesso/source/03-components/figure/figure.stories.jsx
web/themes/gesso/source/03-components/figure/figure.twig

Wasn't sure the best way to handle this - I ended up putting the video gradient/icon/button in the Figure component in case we ultimately want to use the Video component *inside* of the lightbox.

50 - video (thumbnail view, lightbox coming later)

---

web/themes/gesso/source/02-layouts/media/_media.scss
web/themes/gesso/source/03-components/_index.scss
web/themes/gesso/source/03-components/wide-card/_wide-card.scss
web/themes/gesso/source/03-components/wide-card/wide-card.stories.jsx
web/themes/gesso/source/03-components/wide-card/wide-card.twig
web/themes/gesso/source/03-components/wide-card/wide-card.yml

(I opted not to put this under the Card component since it really doesn't act "card-like" in anything but layout.)

87 - wide card (aka tour stop)

---

web/themes/gesso/source/03-components/microsite-hero/microsite-hero.scss
web/themes/gesso/source/03-components/microsite-hero/microsite-hero.twig

Being in the same container as the rest of the hero seems to be the root of the issue.

232 - microsite header stickiness

---

web/themes/gesso/source/00-config/config.design-tokens.yml
web/themes/gesso/source/03-components/_index.scss
web/themes/gesso/source/03-components/embed/_embed.scss
web/themes/gesso/source/03-components/embed/embed.es6.js
web/themes/gesso/source/03-components/embed/embed.stories.jsx
web/themes/gesso/source/03-components/embed/embed.twig
web/themes/gesso/source/03-components/embed/embed.yml
web/themes/gesso/source/03-components/figure/_figure.scss

Nothing too fancy here. The script makes iframes responsive - simple but it seems to work. Potential for issues if the iframe is missing height or width, but I'm pretty sure that wouldn't render correctly anyway & I can't think of anywhere I've seen an iframe without those attributes.

Slac22 88 - embed

---

web/themes/gesso/source/02-layouts/footer/_footer.scss
web/themes/gesso/source/03-components/event-date/_event-date.scss
web/themes/gesso/source/03-components/form-item/_form-item.scss
web/themes/gesso/source/03-components/menu/menu--footer/_menu--footer.scss

- event date adjusted
- footer email adjusted (along with a few other discrepancies in the area i noticed)

Slac22 276 & 281 - design QA

---

web/themes/gesso/source/03-components/card/card-event.yml
web/themes/gesso/source/03-components/card/card-multiday-event.yml
web/themes/gesso/source/03-components/card/card.twig
web/themes/gesso/source/03-components/event-date/_event-date.scss
web/themes/gesso/source/03-components/event-date/event-date.stories.jsx
web/themes/gesso/source/03-components/event-date/event-date.twig
web/themes/gesso/source/03-components/event-date/event-date.yml
web/themes/gesso/source/03-components/event-details/event-details.stories.jsx
web/themes/gesso/source/03-components/event-details/event-details.twig
web/themes/gesso/source/03-components/event-details/event-details.yml

Changed it up so the event date component decides its own layout by comparing a start_date object to an optional end_date, added stories to Event Details to show it off.

253 - update logic for multi-day/multi-month events

---

web/themes/gesso/source/03-components/microsite-hero/microsite-hero.scss
web/themes/gesso/source/03-components/microsite-hero/microsite-hero.twig

Brings the styling closer in line with the other nav, and hides the text in the logo on scroll.

282 - adjust microsite header

---

config/sync/core.entity_form_display.menu_link_content.social-links.default.yml
config/sync/core.entity_form_display.site_setting_entity.share_this_page.default.yml
config/sync/core.entity_view_display.menu_link_content.social-links.default.yml
config/sync/core.entity_view_display.site_setting_entity.share_this_page.default.yml
config/sync/field.field.menu_link_content.social-links.field_icon.yml
config/sync/field.field.site_setting_entity.share_this_page.field_link.yml
config/sync/field.field.site_setting_entity.share_this_page.field_text_list.yml
config/sync/field.storage.menu_link_content.field_icon.yml
config/sync/field.storage.site_setting_entity.field_link.yml
config/sync/field.storage.site_setting_entity.field_text_list.yml
config/sync/site_settings.site_setting_entity_type.share_this_page.yml
config/sync/system.menu.social-links.yml
web/modules/custom/slac_core/src/Plugin/Block/ShareThisPageBlock.php
web/modules/custom/slac_yaml_content/content/share_this_page_site_setting.content.yml

- [SLAC22-73] Add social links menu
- [SLAC22-73] Add social sharing links site setting and block

[SLAC22-73] Social share links and social menu

---

web/themes/gesso/source/03-components/figure/_figure.scss

Fixes the design qa item from the event detail page.

302 - image should fill figure space

---

web/themes/gesso/source/03-components/card/_card.scss

I checked this change against all the card variants in storybook and everything still seems to work.

116 - card image size bug

---

config/sync/core.entity_view_display.node.person.large_card.yml
config/sync/core.entity_view_mode.node.large_card.yml
web/themes/gesso/templates/content/node--person--large-card.html.twig

Pretty much the same as the other person card.

100 - large bio card integration

---

config/sync/core.entity_view_display.paragraph.quote.default.yml
web/themes/gesso/source/01-global/html-elements/16-blockquote/_blockquote.scss

I was using the wrong image style - thumbnail does have the caption hidden already.

99 - quote - fix image & label display, remove extra quotation marks

---

config/sync/paragraphs.paragraphs_type.wysiwyg.yml
web/themes/gesso/gesso.style_options.yml

The link style that is the other half of this ticket is already covered by the small paragraph styling.

128 - allow white background on WYSIWYG

---

web/themes/gesso/source/03-components/hero-bg-image/hero-bg-image.scss
web/themes/gesso/templates/paragraph/paragraph--image-hero.html.twig

Should look more consistent now whether there's a kicker or not.

113 - clean up spacing in image hero

---

config/sync/core.entity_view_display.paragraph.cards_with_show_more.default.yml
config/sync/core.entity_view_display.paragraph.media_card.default.yml
web/themes/gesso/templates/paragraph/paragraph--cards-with-show-more.html.twig

Example: https://integration-slac-w6-d9.pantheonsite.io/node/46

132 - expandable card grid integration

---

composer.json
composer.patches.json
config/sync/views.view.landing_pages.yml

- [SLAC22-368] Set autosubmit for events and news archive
- [SLAC22-368] Apply patch so filters work in viewsreference module

[SLAC22-368] Fix embed view filter issues

---

config/sync/migrate_plus.migration.upgrade_d7_node_complete_lecture.yml
web/modules/custom/slac_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_lecture.yml
web/modules/custom/slac_migrate/src/Plugin/migrate/process/AddOneHour.php

- [SLAC22-225] WIP
- [SLAC22-225] Event migration

SLAC22 225 event migration

---

web/themes/gesso/source/03-components/overlay-link/_overlay-link.scss
web/themes/gesso/templates/media/media--image--poster.html.twig

Also fixes a css issue with the kicker text sometimes being the wrong color.

98 - render name in poster if display name is unset

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/ultimate_cron.job.webform_cron.yml
config/sync/user.role.anonymous.yml
config/sync/user.role.authenticated.yml
config/sync/user.role.author.yml
config/sync/user.role.content_editor.yml
config/sync/user.role.manager.yml
config/sync/user.role.reviewer.yml
config/sync/views.view.moderated_content.yml
config/sync/workflows.workflow.content.yml

- [SLAC22-444] Capture config for webform cron job
- [SLAC22-444] Set permissions for user roles
- [SLAC22-444] Configure workflows

[SLAC22-444] Permissions & workflow

---

composer.lock
composer.patches.json
config/sync/core.entity_form_display.node.homepage.default.yml
config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_form_display.node.media_mention.default.yml
config/sync/core.entity_form_display.node.resource.default.yml
config/sync/core.entity_form_display.node.webform.default.yml
config/sync/views.view.media_library.yml

- [SLAC22-537] Update to Drupal 9.4.6
- [SLAC22-537] More moderation state config updates
- [SLAC22-537] Use full pager on media library

[SLAC22-537] Update core and use full pager on media library

---

config/sync/core.entity_view_display.paragraph.quote.default.yml
web/themes/gesso/source/03-components/quote/_quote.scss
web/themes/gesso/source/03-components/quote/quote.twig
web/themes/gesso/source/03-components/quote/quote.yml
web/themes/gesso/templates/paragraph/paragraph--quote.html.twig

Quote was showing unwanted fields & not correctly linking the citation.

Slac22 412 - quote link bug

---

config/sync/core.entity_view_display.paragraph.quote.default.yml

Fixed this before! but maybe it got regressed, or maybe I forgot to export the config.

412 - fix config for link in quotes

---

web/themes/gesso/templates/media/media--image--full.html.twig

per linda - 'Yes, please show the description and if no description is in the field, have the caption show up on the detail page. '

470 - show description on image detail page if present

---

web/sites/default/settings.php

Added config split logic to settings.php

Slac22 603 bed install config split

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/language.content_settings.node.event.yml
config/sync/language.content_settings.node.homepage.yml
config/sync/language.content_settings.node.landing_page.yml
config/sync/language.content_settings.node.media_mention.yml
config/sync/language.content_settings.node.news_article.yml
config/sync/language.content_settings.node.page.yml
config/sync/language.content_settings.node.person.yml
config/sync/language.content_settings.node.resource.yml
config/sync/node.type.event.yml
config/sync/node.type.homepage.yml
config/sync/node.type.landing_page.yml
config/sync/node.type.media_mention.yml
config/sync/node.type.news_article.yml
config/sync/node.type.news_collection.yml
config/sync/node.type.page.yml
config/sync/node.type.person.yml
config/sync/node.type.resource.yml
config/sync/search_api.index.content.yml
web/modules/custom/slac_core/src/Plugin/search_api/processor/ExcludeHiddenMedia.php

- [SLAC22-651] Exclude hidden media from search
- [SLAC22-651] Allow content to be excluded from site search

[SLAC22-651] Search result UAT

---

web/themes/gesso/source/03-components/microsite-hero/microsite-hero.es6.js
web/themes/gesso/source/03-components/microsite-hero/microsite-hero.twig

- Remove search from desktop
- Link SLAC logo in mobile menu to homepage

Updates to microsite hero

---

config/splits/local/simplesamlphp_auth.settings.yml
config/sync/config_split.config_split.local.yml
config/sync/config_split.config_split.prod.yml

Fixing problem where lack of settings file for simplesamlphp_auth module reults in infinite loop from `/user/login` to /`saml
_login`.  Added conditional split for that file.

Slac22 19 bed sso 2

---

config/sync/field.field.paragraph.video_lightbox.field_body.yml
web/themes/gesso/includes/paragraph.inc

- [SLAC22-684] Set paragraph as cacheable dependency for media in lightbox
- [SLAC22-684] Add url cache context

SLAC22 684 video lightbox override caption cachecontext

---

web/themes/gesso/source/03-components/filter-modal/filter-modal.es6.js

https://forumone.atlassian.net/browse/SLAC22-667

SLAC22-667: remove page from url params on facet update

---

config/sync/facets.facet.entity_type_grid.yml
config/sync/facets.facet.entity_type_list.yml

https://forumone.atlassian.net/browse/SLAC22-700

SLAC22-700: require min 1 result for type facets

---

web/themes/gesso/includes/node.inc

https://forumone.atlassian.net/browse/SLAC22-459

SLAC22-459: increase field_body_trimmed trim_length from 500 to 530

---

config/sync/core.entity_form_display.media.remote_audio.default.yml
config/sync/core.entity_form_display.media.remote_video.default.yml

https://forumone.atlassian.net/browse/SLAC22-572

SLAC22-572: hide transcript field in details group

---

config/sync/antibot.settings.yml
web/themes/gesso/templates/form/form.html.twig
web/themes/gesso/templates/form/webform.html.twig

https://forumone.atlassian.net/browse/SLAC22-701

Slac22 701 install antibot and spam words modules

---

web/themes/gesso/includes/node.inc

https://forumone.atlassian.net/browse/SLAC22-459

SLAC22-459: use smart_trim field formatter

---

composer.json
composer.lock
web/themes/gesso/source/02-layouts/header/header.twig
web/themes/gesso/source/03-components/microsite-hero/microsite-hero.scss
web/themes/gesso/source/03-components/microsite-hero/microsite-hero.twig
web/themes/gesso/source/03-components/mobile-menu/modules/_MobileMenu.es6.js

- [SLAC22-705] - Updated header to remove issue with microsite. Updated microsite hero to fix issue with logo.  Updated menu wording for screen readers.
- Remove upstream-configuration and update lock file

[SLAC22-705] Microsite header regression fix

---

web/modules/custom/slac_core/src/Callback/LinkPreRender.php
web/modules/custom/slac_core/src/Callback/TextPreRender.php
web/themes/gesso/gesso.libraries.yml
web/themes/gesso/includes/html.inc
web/themes/gesso/includes/paragraph.inc
web/themes/gesso/templates/paragraph/paragraph--image-hero.html.twig
web/themes/gesso/templates/paragraph/paragraph--two-column-hero.html.twig

- Remove unneeded selection-sharer es6
- Remediate text formatting / missing text issues

Hotfix 2-8-22

---

web/modules/custom/slac_core/src/Callback/LinkPreRender.php
web/modules/custom/slac_core/src/Callback/TextPreRender.php
web/themes/gesso/gesso.libraries.yml
web/themes/gesso/includes/html.inc
web/themes/gesso/includes/paragraph.inc
web/themes/gesso/templates/paragraph/paragraph--image-hero.html.twig
web/themes/gesso/templates/paragraph/paragraph--two-column-hero.html.twig

- [SLAC22-705] - Updated header to remove issue with microsite. Updated microsite hero to fix issue with logo.  Updated menu wording for screen readers.
- Remove upstream-configuration and update lock file
- Remediate text formatting / missing text issues
- [SLAC22-707] - Add External Link JS to Libraries.
- Remove unneeded selection-sharer es6

Hotfix 2-8-22 (Live)

---

config/sync/core.entity_view_display.media.image.two_column_hero.yml
config/sync/core.entity_view_display.node.person.card.yml
config/sync/core.entity_view_display.node.person.default.yml
config/sync/core.entity_view_display.node.person.full.yml
config/sync/core.entity_view_display.node.person.large_card.yml
config/sync/core.entity_view_display.node.person.teaser.yml
config/sync/core.entity_view_display.taxonomy_term.tags.full.yml

- [SLAC22-697] Use card image style for topic heading
- Revert "Adjusts image style for topic pages"
- [SLAC22-697] Schema updates

[SLAC22-697] Update topic header image style

---

web/themes/gesso/source/03-components/search/search.es6.js
web/themes/gesso/source/03-components/search/search.twig

710 - remove 'slac web' search option

---

web/themes/gesso/source/03-components/mega-menu/mega-menu.es6.js
web/themes/gesso/source/03-components/search/_search.scss

Most of the code for this already existed and just needed to be turned on.

711 - show quick links in mobile menu

---

web/themes/gesso/source/00-config/config.design-tokens.yml
web/themes/gesso/source/03-components/promo-box/promo-box.twig

Per Jenny's request, with an exception to keep the promo box title its current size.

720 - globally increase h2 size to match section title

---

web/themes/gesso/source/03-components/video-lightbox/video-lightbox.twig

There weren't a lot of details in the ticket but I think this should cover the request.

Slac22 723 - video lightbox label

---

config/sync/sitewide_alert.settings.yml
web/themes/gesso/source/03-components/alert-bar/alert-bar.scss

@briantschu Feel free to change the base for this if you end up setting up another support sprint branch.

730 - add blue alert bar style
