SLAC/W6-D9

- web/themes/gesso/source/02-layouts/footer/_footer.scss
- web/themes/gesso/source/03-components/social-links/_social-links.scss
The ticket called out the space above the links & wanting to turn off the hover colors in this area; I also adjusted the size to get it closer to designs. Left the hover colors in case they're still needed outside of the footer.
@kmonahan for some reason, [icons](https://integration-slac-w6-d9.pantheonsite.io/themes/gesso/storybook/?path=/story/components-icon--icon) aren't showing up on [integration](https://integration-slac-w6-d9.pantheonsite.io/themes/gesso/storybook/?path=/story/layouts-footer--footer) - they're fine on this branch and it's been merged in, so I'm not sure what's up.
> 208 - minor cleanup in footer social menu

- web/themes/gesso/source/00-config/mixins/_link.scss
- web/themes/gesso/source/03-components/_index.scss
- web/themes/gesso/source/03-components/kicker/_kicker.scss
- web/themes/gesso/source/03-components/overlay-link/_overlay-link.scss
- web/themes/gesso/source/03-components/overlay-link/overlay-link.stories.jsx
- web/themes/gesso/source/03-components/overlay-link/overlay-link.twig
- web/themes/gesso/source/03-components/overlay-link/overlay-link.yml
Made one component that both the topic & poster can use for their hover stylings.
I used `arrow-link` but had to turn off the whitespace override to keep the title fitting into the card; we may need to find a different solution for keeping the arrow inline, if that's important to the client.
> 91 & 56 - topic & poster FED

- web/themes/gesso/source/03-components/overlay-link/overlay-link.stories.jsx
- web/themes/gesso/source/03-components/overlay-link/overlay-link.twig
- web/themes/gesso/source/03-components/overlay-link/overlay-link.yml
- web/themes/gesso/source/03-components/topic-grid/topic-grid.yml
Added lazyloading & set images in this grid to use dimensions if possible - this will keep masonry from breaking too much if an image fails to load.
This is the most basic browser-level lazyloading; I think it'll be enough for their purposes but it's been a little tough to realistically test inside of storybook/with placeholder images. I think we'll have a better sense of whether we need more once it's integrated & pulling real images.
> Slac22 94 - topic grid updates

- web/themes/gesso/source/03-components/embed/_embed.scss
- web/themes/gesso/source/03-components/embed/embed.es6.js
- web/themes/gesso/source/03-components/map/map.yml
This should fix the issue we were seeing with the google map. Only iframes in the 'embed' component will get resized with this script now.
> 268 - rework responsive iframe code

- web/themes/gesso/source/03-components/filter-modal/_filter-modal.scss
- slight text-indent to keep focus outlines from cutting off in mobile
- set a height so the container becomes scrollable if content is too tall (for short laptops etc)
> 53 - filter modal visual overflow tweaks

- web/themes/gesso/source/03-components/tagline/tagline--long/tagline--long.scss
Adds some padding to avoid overlap with the icons & limits the line-length to a reasonable width. The gutter was a little wider than the designs so I adjusted that too.
> 301 - design qa tweaks on tagline (our story)

- web/themes/gesso/source/01-global/html-elements/01-html/_html.scss
- web/themes/gesso/source/01-global/html-elements/15-inline-elements/_inline-elements.scss
- scroll-padding-top keeps anchor targets from hiding behind the header
- inline empty anchors take up 1 line-height, throwing off the scroll position; block ones don't
> Slac22-300 - adjust microsite anchor links scroll position

- web/themes/gesso/source/03-components/button/_button.scss
Prevent chevron & external icon from showing at the same time, add a little spacing to the external button icon so the buttons look more consistent, fix a color mismatch in one of the secondary styles.
> 315 - fix issue w/external button links

- web/themes/gesso/source/03-components/page-title/_page-title.scss
Keeps things from looking cramped if the lede is empty.
Example: https://integration-slac-w6-d9.pantheonsite.io/node/40
> 152 - account for page title followed directly by author

- web/themes/gesso/source/03-components/pager/_pager.scss
- use the default focus styles for these links for better visibility; tweak the size so they're consistent with the numbers
- switch to mini-pager at a larger size to account for the widest possible content
> 122 - pager - fix mobile & focus issues

- web/modules/custom/slac_core/slac_core.module
- web/modules/custom/slac_core/src/Entity/Event.php
@kmonahan event "tense" API, template use:
{{ node.isPastEvent() }} : returns bool
{{ node.getEventTense() }} : returns translated string
Dates are regularized to default timezone. Also note that an event is only "past" if the event's end date/time is before the current date/time -- if the start date/time is before the current date/time but the end date/time is after the current date/time, the event is not considered past, it is "in progress"
> [SLAC22-326] Event bundle class for event tense and past event badging

- web/themes/gesso/source/03-components/cookie-banner/_cookie-banner.scss
we do lose the slide-down-and-out animation when you're 100% scrolled with this, but that seems acceptable compared to blocking footer logos.
> 407 - keep cookie bar from obscuring footer

- web/themes/gesso/source/02-layouts/header/_header.scss
The height is eyeballed based off their screenshot; they should probably go back and update this in figma to avoid future confusion.
> 474 - larger mobile logo for brand reasons

- .github/workflows/build_deploy_and_test.yml
- [SLAC22] Pin deploy image to specific version
- [SLAC22] Use dockerhub SHA'd version instead of quay
After a recent update to the pantheonpublic/build-tools-ci docker image, our builds were failing due to a git error: `fatal: detected dubious ownership in repository at '/__w/W6-D9/W6-D9'`. Reverting to 
the prior container image seems to resolve the issue. I suspect this is due to a change in the underlying image the container is being built from.
> [SLAC22] Pin container image for deployments

- web/themes/gesso/source/03-components/toc/toc.es6.js
- web/themes/gesso/source/03-components/toc/toc.scss
This one was interfering with the usability of the UI, so I'd call it a blocker. Granted - this fix is going to make it disappear in storybook, but at this stage of the project, that seems acceptable.
The css change is just to line it up better visually.
> 406 - fix icon path for TOC chevron

- web/themes/gesso/source/03-components/alert-bar/alert-bar.scss
As far as I can tell, there's no reason to limit the height on the bar.
> 473 - fix cut-off text in alert bar

- config/sync/pathauto.pattern.events.yml
Per https://forumone.atlassian.net/browse/SLAC22-583, updated Event pathauto pattern to use event start date instead of node created date.
> SLAC22-583: change event pathauto pattern

- config/splits/local/.htaccess
- config/splits/prod/.htaccess
- config/splits/prod/google_tag.container.main.yml
- config/sync/config_split.config_split.local.yml
- config/sync/config_split.config_split.prod.yml
- config/sync/core.extension.yml
This PR covers two tickets:
https://forumone.atlassian.net/browse/SLAC22-329
https://forumone.atlassian.net/browse/SLAC22-603
The GTM container in the first ticket is configured via config split for the prod environment in the second ticket.  Testing locally requires a `settings.local.php` file with the following lines included:
```
$config['config_split.config_split.prod']['status'] = TRUE;
$config['config_split.config_split.local']['status'] = FALSE;
```
The GTM container will install by default.  To test the config split, change prod to FALSE and local to TRUE, clear cache and import config.
> SLAC22-603: SLAC22-329, config split and GTM configured

- web/themes/gesso/source/03-components/icon-card/icon-card.scss
All cards in a row in the 'small card with icon' style will be equal height.
> 698 - icon card height equalized

- web/themes/gesso/templates/content/taxonomy-term--tags--full.html.twig
- web/themes/gesso/templates/field/field--media--field-caption--image--tooltip.html.twig
- web/themes/gesso/templates/field/field--media--field-credit--image--tooltip.html.twig
- web/themes/gesso/templates/paragraph/paragraph--article-hero.html.twig
- web/themes/gesso/templates/paragraph/paragraph--image-embed--two-column-hero.html.twig
- web/themes/gesso/templates/paragraph/paragraph--image-hero.html.twig
- web/themes/gesso/templates/paragraph/paragraph--microsite-hero.html.twig
- web/themes/gesso/templates/paragraph/paragraph--overlap-image.html.twig
Per Jenny's request, this moves the caption & credit onto one line in image tooltips. (The "image details" link, if present, is still on a separate line.) 
Several examples here - https://integration-slac-w6-d9.pantheonsite.io/research/x-ray-and-ultrafast-science
(The hero caption breaks onto separate lines, but this is a coincidence based on text length.)
> 725 - caption spacing adjustment

- web/themes/gesso/source/03-components/card/_card.scss
Request was to make the aspect ratio match other search cards. No change to the cards as viewed outside of search (leadership listing pages etc)
> 722 - adjust person cards

- web/themes/gesso/source/03-components/promo-box/_promo-box.scss
Meant to lock down this font size when we updated the global styles.
> fix regression in promo box title size (slac22-720)

- config/sync/core.entity_view_display.media.image.video_lightbox_no_caption_credit.yml
- config/sync/core.entity_view_display.media.remote_video.video_lightbox_no_caption_credit.yml
- config/sync/core.entity_view_display.node.event.full.yml
- config/sync/core.entity_view_mode.media.video_lightbox_no_caption_credit.yml
- web/themes/gesso/includes/media.inc
- web/themes/gesso/source/03-components/event-details/event-details.scss
- web/themes/gesso/source/03-components/event-details/event-details.twig
- web/themes/gesso/templates/media/media--image--video-lightbox-no-caption-credit.html.twig
- web/themes/gesso/templates/media/media--remote-video--video-lightbox-no-caption-credit.html.twig
I didn't see a good way to do this from the markup side (didn't want to affect captions on other uses of the video component), so I've just hidden it with css.
example: https://integration-slac-w6-d9.pantheonsite.io/events/2022-10-06-charging-ahead-batteries-future
> 729 - hide caption on event detail
